### ISSUE TITLE
storage: add "proxycache" storage type

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#443]
<pre>The FUSE code already does its own caching of blobs, but that code isn't available via a
registered storage type.

We should add pkg/blobserver/proxycache adding the &quot;proxycache&quot; storage type,
which requires:

-- an &quot;origin&quot; storage prefix
-- a &quot;cache&quot; prefix.
-- a &quot;maxCacheSize&quot;
-- a &quot;usageMeta&quot; sorted.KeyValue for tracking access times

Related: <a href="https://camlistore.org/issue/443">issue #443</a> so diskpacked can be an efficient cache.</pre>

**Comment by stephens2424** [comment]
Just as an fyi, I've started working on this [here](https://github.com/camlistore/camlistore/compare/master...stephens2424:proxycache?expand=0). I've got a few things to fix and clean up before I'd call it review-ready. This basically fills in a few TODO items I found in proxycache and adds some tests. The approach steps away from sorted.KeyValue and uses the lru package and the stats blobserver. There's a bit of redundant data being stored, so I'm not in love with it... but I do think the implementation is simpler using the imports. Still hacking a bit, but feel free to make suggestions if you find the time.

**Comment by edrex** [comment]
A nice (later) validation of this might be to remove the caching code from `pkg/fs` and have `cmd/cammount` wire one up at runtime (maybe with a flag to turn it off, which could be useful for debugging cache issues).

**Comment by stephens2424** [comment]
This change is getting close, so I uploaded to the [review server](https://camlistore-review.googlesource.com/#/c/8926/) in case anyone wants a head start.

**Comment by stephens2424** [comment]
Something in particular I could use a little input on: when we verify the cache, what should we do with the different errors?

- cache is missing a ref the caller asked to check
this seems like an easy call to just return the error here.

- origin is missing a ref the cache has
This probably means the item was deleted from the origin. Should we just delete it in the cache? Or should we put it back onto the origin?

- the size of refs in the origin and cache differ
In theory, this means a hash collision, but it's possible this case will occur at some point because of a bug of some kind. Maybe actually panic in this case? Lots of hi-jinx could probably happen if equal refs could show up with differing sizes (i.e. different content)

**Comment by stephens2424** [comment]
So I went with returning an error in all the cases. (Only when you ask to verify specific refs does the cache missing a ref actually become an error)

I decided to punt on the BlobHub issue for now, but I think that's okay. Deleting blobs seems like it'd be a rare use case and changing them would involve finding a hash collision ... so even more rare.

I also think I found a bug in the go4.org/jsonconfig package while writing a test for the configuration piece of this. That last test is currently failing, but passes with this change applied: https://review.gerrithub.io/#/c/346661/.

Apart from that last item, this change is "done" and I would be delighted with some code review :)

https://camlistore-review.googlesource.com/#/c/8926/
