### ISSUE TITLE
twitter: over-escaping in the web UI

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#476]
<pre>If you write &quot;&amp;&quot; or &quot;&lt;&quot; in a tweet, it renders as
over-escaped in the web UI.

See screenshot
.</pre>

Attachments:

1. <a href="https://storage.googleapis.com/camlistore-issue-attachment/476/0/over-escape.png">over-escape.png</a> (19934 bytes)

**Comment by kereyroper** [comment]
twitter-text was moved to here:
https://github.com/twitter/twitter-text

It looks like they HTML encode a subset of the dangerous HTML characters since presumably the text field won't be used in an HTML attribute, but they are missing backtick ` in any case. This lines up with sample data I have.

Overall, it's a very strange approach to an API since the result is JSON and should only be JSON escaped.

**Comment by edrex** [comment]
Fixed (with tests) by https://camlistore-review.googlesource.com/6486

**Comment by mpl** [comment]
@edrex we should keep track on how you trimmed the test data in the zip file. Can you please add a README in the testdata dir to explain that? Or even a program if it's more that a couple of commands?
