### ISSUE TITLE
camput: -verbose is not verbose

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#525]
<pre>I ran:

$ camput -verbose file  -filenodes -delete_after_upload *.JPG

And I've been waiting several minutes and I see no output.

The verbose is not verbose enough.</pre>

**Comment by mpl** [comment]
Whatever the problem was, it looks verbose enough to me now:

% camput -verbose file -filenodes -delete_after_upload /home/mpl/tmp/lans/IMG_20130302_1*
sha1-a2bde74ae70e63adcf1697719c11f4ca3cb6cedf
sha1-369f8416c89dbc6cab251962b89460dca6c75709
2016/03/03 15:51:37 Deleted /home/mpl/tmp/lans/IMG_20130302_151134.jpg
sha1-a1d284d167fd7396e8b494484c70201e4d04807d
sha1-2cbb2a28246f693f06977e48b77ba53b4799d284
sha1-f98a9af027426eaae17fe59a3763099c18cb02e1
2016/03/03 15:51:38 Deleted /home/mpl/tmp/lans/IMG_20130302_151142.jpg
sha1-6df523e676beccc2de3ba6116d32055d5b3c9f77
sha1-b9477d191118d5b6740acd77c2467e2c65064c5d
sha1-64dd085bd652621980bb2d5b0d46bd69befae0db
2016/03/03 15:51:38 Deleted /home/mpl/tmp/lans/IMG_20130302_151153.jpg
sha1-77396c0a7194f7b0b70bf062a04a96c3a993f018
sha1-74236fca7d43c86dea2cf6f295aa3a5d0ea41b84
sha1-49ec91eff4758dc8bc2a361d00f6f521b1316592
2016/03/03 15:51:39 Deleted /home/mpl/tmp/lans/IMG_20130302_151205.jpg
sha1-a19bd9eefdbe0c09fdb41c40432c10072b6227bc
sha1-45b7baec73a908ef1dc9941ebce0361f799d175d
sha1-4669edf57e47e9537f1c3eb8af8d1ce9113b35a2
2016/03/03 15:51:39 Deleted /home/mpl/tmp/lans/IMG_20130302_164137.jpg
sha1-d7f7b59faa75a6239032415b432d9eb59385cf36
sha1-8997b1acc886baeab4b2c7b6f0680a4265233172
sha1-e70a2984466290ae3f40e30cbe82a423651f6d0b
2016/03/03 15:51:40 Deleted /home/mpl/tmp/lans/IMG_20130302_164154.jpg
sha1-91ac303225d988499d2bde5068779489970cffea
sha1-29f242296aac5e7b5db01e537950a6944153a4ec
sha1-14ea570bedf671b57862985a4922b144f9045acf
2016/03/03 15:51:40 Deleted /home/mpl/tmp/lans/IMG_20130302_164213.jpg
sha1-85c52f662a9e5d2d4609e38e6eaab511630996ed
sha1-d0a5fbf8b354867e7572029cea5b3086c053e1cf
sha1-2ea314eb3628489a102f5d999360780a4238d103
2016/03/03 15:51:40 Deleted /home/mpl/tmp/lans/IMG_20130302_164239.jpg
sha1-83e07ea01a952a39132b5877d17324d87ae35069
sha1-2869adeb54439b03b9fd97129c6d0f96dcd3969c
sha1-7661e4367558fc75cab04ff847fa378d10298f5a
2016/03/03 15:51:41 Deleted /home/mpl/tmp/lans/IMG_20130302_164259.jpg
sha1-b0849d45b3aa780a7abf91be7209122c8c115be5
sha1-b81f74422c4eca85258707aee2846bd3bbf13cf7
sha1-b1d8cff0763b04cdd26fbbd6994337ee0b18df68
2016/03/03 15:51:41 Deleted /home/mpl/tmp/lans/IMG_20130302_164344.jpg
sha1-3751844210f0f43a39395fba849d07dadd44186d
sha1-0947f6fe6a09d603b85d01bb3b1b63ca7ffdbe9c
sha1-a51e49f9befcd388a96a3acc50099e56e85ceeee
2016/03/03 15:51:42 Deleted /home/mpl/tmp/lans/IMG_20130302_164412.jpg
sha1-d0473488cfd2e88c8084a3759f6122b72ce0ed10
2016/03/03 15:51:42 Client stats: [uploadRequests=[blobs=553 bytes=32838374] uploads=[blobs=553 bytes=32838374]]
2016/03/03 15:51:42   #HTTP reqs: 587
2016/03/03 15:51:42    responses: 587 (h1), 0 (h2)
