### ISSUE TITLE
web UI does not show the number of selected items

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#585]
I'm pretty sure the UI used to tell you somewhere how many items are selected at any given time, and I find that I miss this feature. Most often when I want to double-check that all the items I've just camputed are all accounted for in the set I'm viewing, but that's just one case.

@aboodman @dotMR I'd assume this is pretty easy to do, so if you guys don't have time, please let me know and I'll try to have a go at it.

**Comment by aboodman** [comment]
The sidebar used to say, e.g., "Add 5 items to set", rather than the current "Add items to set".

I think it was changed because it felt repetitive to have the number in every button, and also the wording was a bit awkward in some cases. For example "Create set with 5 items" isn't very clear that it's talking about the 5 *selected* items.

I think it might be better to add a text header to the sidebar that says "5 items selected". Then the text of the buttons can remain the same.

You can look at git blame for the sidebar to see how getting the number of selected items used to work. I think it is basically just goog.object.count(this.state.selection) or something.

**Comment by aboodman** [comment]
I won't be able to do this until week of March 22. If you want to do it before then, please feel free.

**Comment by aboodman** [comment]
Nevermind, here is a patch: https://camlistore-review.googlesource.com/#/c/4787

**Comment by dotMR** [comment]
I like having a count of the items selected in the sidebar. We had it in the prototype at one point but must have gotten lost in the iterations.

**Comment by mpl** [comment]
Excellent, thanks!
Done by: cd072f78cd6393302eccdea5b9e76f23385a0d33
