### ISSUE TITLE
How will GCE users update from 0.9 to 0.10?

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#588]
Once we have the Camlistore web wizard instance creator launched and 0.9 is out, how will those users later upgrade to 0.10?

* via the launch wizard again? with prompts about upgrades?
* via some camlistored driven process? (should that be in 0.9?)
* via the GCE web UI, setting some metadata key and restarting? how do they restart the server? from the GCE UI, or camlistored UI?
* via ssh? lame.
* via gsutil? lame.

We should at least come up with a plan before 0.9 ships, in case we need something in 0.9 to make the 0.9->0.10 upgrade easier, or at least to keep our options more open.

/cc @mpl

**Comment by cliveb** [comment]
On a similar design during startup we compare server-config.json with master-config.json for version. 

0.9 = 0.9  nothing to do
0.10 = 0.10  nothing to do 

When server-config.json is 0.9 and master-config.json is 0.10 this triggers an upgrade process that makes any database client and server metadata and configuration changes. This comparison proved robust. 

Only when folks do unexpected things (and they do) such as restore an older master version, so that server-config is 0.10 and master-config is 0.9 (0.10<-0.9) did we end up with a "hangman".  Here we no instantiate art, we have no idea what has transpired. http://en.wikipedia.org/wiki/Hangman_(game)#/media/File:Hangman.svg

It may be too much to expect web access to camlistore.org/config-master.json or github.com/camlistore/config-master.json and instead check locally and compare .config/camlistore/server-config.json
.config/camlistore/master-config.json

**Comment by bradfitz** [comment]
I think we can just make the 0.10 setup wizard find their existing instance, look at its metadata and config in GCS, destroy the VM, and create a new VM with the right metadata to do an upgrade.

I don't think we need to do anything for 0.9.

**Comment by cliveb** [comment]
Makes sense. Good plan on closed #588
<https://github.com/camlistore/camlistore/issues/588>

Currently, I am pretty sure only a couple of GCE 0.8 cloud launcher
versions are out in the wild. Most Camli launcher instances self-terminate
(or go dormant) after the free Google Cloud Platform developer trial
credits expire. Even a small GCE cpu version costs about $15.00 - $20.00 /
month just on hosting tick over with no monthly read write activity.

If would be nice to figure out how to Kubernetes Camlistore launcher
version to reduce $20 to say $2. I think @brendandburns
<https://twitter.com/brendandburns> said maybe 20 or more IP addresses per
Kubernetes container (he hadn't tested how many beyond 20-ish). I think
there's a lot of thrifty Moms who care about their kids / fam photos).

Thanks
cliveb.github.io/


On Thu, Dec 24, 2015 at 11:00 AM, Brad Fitzpatrick <notifications@github.com

**Comment by mpl** [comment]
@cliveb fwiw https://www.scaleway.com/imagehub/camlistore/ is probably less expensive than Google Cloud, at least for the base cost. But I should update it.
