### ISSUE TITLE
devcam: install git hooks

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#590]
devcam should have a command to install the git hooks.

And the git hooks should be implemented in Go, in devcam.

e.g. see how Go's git-codereview works:

```
bradfitz@laptop go$ cat .git/hooks/commit-msg
#!/bin/sh
exec git-codereview hook-invoke commit-msg "$@"
bradfitz@laptop go$ cat .git/hooks/pre-commit
#!/bin/sh
exec git-codereview hook-invoke pre-commit "$@"
```

We should do the same, and kill all shell.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5297

**Comment by mpl** [comment]
6fa15a228e50935fb91521d0ea967a6a919b580c
9a24acca6cea06a56be595d903c89a2d683a0380

not closing yet, because commit-msg is still a bash-script.

However, I'm thinking, seeing as it seems to be an "official" gerrit hook, that instead of porting it to go, devcam hook commit-msg could just be an os.Exec of that script, no?

oh, except git-codereview probably has the equivalent too, since Go uses gerrit too. Will look again.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/6042 for commit-msg

**Comment by josephholsten** [comment]
@mpl is there anything remaining for this CL?

**Comment by mpl** [comment]
@josephholsten you meant s/CL/issue/ right? and no, nothing left, we can close it. thanks.
