### ISSUE TITLE
Redirect / to /ui/

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#593]
If the root handler detects that the /ui/ handler is installed, and the request path is exactly "/" (and not even "/?") then redirect to /ui/ for a warmer welcome.

The UI links to /status/ nowadays anyway.

**Comment by saljam** [comment]
While we're at it, can we make the redirect target URL an (optional) parameter in the root handler's config? With "/ui/" as the default value.

I'd like my "/" to redirect to a publisher. (Better still, I'd like "/" to be handled by an app handler rather than the root handler, but that might need a bit more work.)

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/4967

@saljam SGTM, but I haven't addressed it in that CL.

Feel free to do it in another CL? :-)

**Comment by mpl** [comment]
89488a3cf4a326b56015885973467cae17982b7e

@saljam feel free to reopen if/when you want to give a go at your proposition.
