### ISSUE TITLE
Update text “The server says: camlistored” in auth

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#595]
The camlistored auth handler has this weird text:

> “The server says: camlistored”

Why?

I guess it means that the username must be "camlistored".  But why does the username matter? We don't support multiple users yet anyway.

We could just ignore the username and change the text to say "Any username works. Password is available from (LINK TO COMPUTE GCE INSTANCE URL METADATA)"

**Comment by mpl** [comment]
We cannot change that part of the text: "The server says:", as it is added to the dialog by the browser (the text is slighly different on firefox) because we sent back a realm (which is "camlistored" != username).

What we could do is:

1) Nothing. because realms can be used to separate different auth domains. maybe we'll want a different auth for a different part of what we serve? I don't know.

2) send an empty realm. I've checked that both on chrome and ff, that makes the whole "The server says..." string disappear.

3) use the realm as a hint for where to find the username/password, like you suggested (when I assume you had forgotten it was about the realm). but it now seems to me that it's not what it's meant for and it would be kinda gross, no?

**Comment by bradfitz** [comment]
Empty realm works.

**Comment by mpl** [comment]
sgtm, will do.

**Comment by mpl** [comment]
e13dc9a0ce2b8bb7e7110470692c8344a013fce0
