### ISSUE TITLE
Future React upgrades will require a change to how we call components

### ISSUE THREAD

**Issue by dotMR** [camlistore/camlistore#607]
The auto-generated component factory is now deprecated.
https://gist.github.com/sebmarkbage/d7bce729f38730399d28

**Comment by mpl** [comment]
it does not seem like a difficult migration, does it? a bit tedious at worst?

**Comment by dotMR** [comment]
No, not difficult. I just added the issue so there was context for a commit message.

I think mostly it will be operations like this:
"React.DOM.div(" -> "React.createElement('div', "

They also [depracated React.addons.classSet](https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html#deprecations), which we use in a few places.

You can assign to me. I don't think there is an immediate reason to upgrade, but the technology is moving pretty quickly right now. It maybe better to try to keep-up if we can.

**Comment by edrex** [comment]
I am working on upgrading to React 0.15, a lot of breakage.

**Comment by mpl** [comment]
@edrex I'm not sure that's the best direction since, if possible, we'd eventually fully go the gopherjs route (which does not support React yet).

Similarly, I had a CL on updating closure https://camlistore-review.googlesource.com/5736 which I stopped working on when I realized we were doing gopherjs.

**Comment by edrex** [comment]
Maybe gopherjs and React can coexist, at least in the short term? I'd hate to have the whole UI inoperable in master until every bit has been ported to a new UI system. Anyway, this is pretty much working, so I'll put it up: https://camlistore-review.googlesource.com/6597

**Comment by edrex** [comment]
@mpl, it seems like you're suggest that we freeze development on the current web UI layer while a GopherJS-based replacement is developed.

I'm not opposed to using GopherJS for the web UI, but before we freeze the current UI I think we should map out a transitional plan. If we aren't, then I think we should continue to support and maintain the React-based UI.

**Comment by mpl** [comment]
I need to finish testing something out before I can answer that. I hope to be done today.

**Comment by mpl** [comment]
@edrex 

First off, I believe React and gopherjs are quite incompatible, because:
1) There are no working react bindings for gopherjs, that I know of.
2) As soon as you have a react component, anything within it needs to be created with react methods such as React.DOM.Div(), and (I think) we can't do that with Go/gopherjs. So we would be able to replace bits with gopherjs, but anything that touches the dom would have to stay React.

So speaking of a transitional plan, the above might be one way to go: replace everything we can that does not touch react (e.g. all the xhr and queries in server_connection) with gopherjs. But:
1) I think there isn't much that isn't react, so we'll hit a wall pretty soon.
2) Most of the things we want to work on are UI features, so most likely already react. And we don't want to do javascript anymore.

It seems the other plan is indeed to start redoing all of the existing stuff with gopherjs, which does not prevent adding new features along the way btw. But it would probably sort of look like a freeze for a while.

To start on that plan, we're waiting on two (loosely) interdependent things:
1) To be confident that we can do everything we want with gopherjs + bindings
2) That Brad gives me the green light to land https://camlistore-review.googlesource.com/5816

For 1) I wanted to push experimenting with gopherjs a bit further, so what I was working on is:
https://camlistore-review.googlesource.com/6608
which now makes me pretty confident about gopherjs. That is, if we can overcome the potential problem that is the large gopherjs.js file generated.

Finally, another route (which had been the initial plan for a while) might be an experimental/conditional UI with gopherjs. make.go would keep on building the old/React UI by default, so that you and others can keep on working on it in javascript if they want. While I would be working on the new one (gopherjs/no react) in the meantime. Until I'm completely caught up with the React version, which we could then deprecate.

ping @bradfitz

**Comment by dotMR** [comment]
@mpl out of curiosity, I know your personal feelings about JS, but what is the reasoning for abandoning JS/React? Is it a lack of current UI contributors?

My unsolicited opinion, but starting over with the UI seems like a few steps backward and a long road to hopefully get back to status quo (the generated file size seems to be a pretty common concern for GopherJS). And agreed to not count on gopherJS + React to work reliably anytime soon.

**Comment by mpl** [comment]
@dotMR Yes, the ongoing lack of contributors is the main reason. We figured we could wait forever for contributors OR we could switch to gopherjs which at least ensured that Brad and I would eventually get things done on the UI, because we wouldn't be put off by having to do JS.
Not to mention the Go contributors we already have would perhaps then be tempted into doing UI work as well.

**Comment by bradfitz** [comment]
I also share @dotMR's concern that we'd be starting from scratch on the UI. Maybe that's kinda okay, though, since we don't totally love what we have now.

But it'd be nice to build on top of common JavaScript UI libraries that are actively developed.

Can we do GopherJS + Polymer or ..... ? I don't know what's necessarily hip in JS widget/framework space these days.

Worst case TypeScript seems to have good tooling and bindings to everything and a lot of staffing. And @martine raves about it.

Whichever route we go, I think we're kinda starting over, though. The current JS + React thing is okay, but like @mpl says, neither of us are hacking on it often. That could also be because we're busy, too. But I'd like something less JavaScript and more statically typed. We tried Closure. It was painful. (slow compiler, and more time fighting the annotations than them being useful). GopherJS would be nice to support and improve. TypeScript seems to have a lot of momentum already, and growing.

**Comment by edrex** [comment]
> 2) As soon as you have a react component, anything within it needs to be created with react methods such as React.DOM.Div(), and (I think) we can't do that with Go/gopherjs. So we would be able to replace bits with gopherjs, but anything that touches the dom would have to stay React.

I haven't played with GopherJS, but from the README it sounds like maybe `js.Global.Get("React.DOM").Call("Div")` should work?

> That is, if we can overcome the potential problem that is the large gopherjs.js file generated.

It looks like this is the space to watch: https://github.com/gopherjs/gopherjs/issues/186

The thing I can't quite get over with GopherJS is the monolithic output. That's often fine for a web app, but also sometimes dynamic linking is useful: code sharing between different pieces of the system without having to bundle them together, also interoperability with other stuff in the runtime.

---

React is still marginally hip right? Negative feels about it? There are lots of other tools out there. 

I keep poking at Polymer and running away. I can't shake the feeling that it's held together by chewing gum. I love the concept of multi-vendor components coexisting on a page. Also the paper elements would give us a library of ready to go UI components. Not opposed.

I also hear good things about Typescript. Since it's a super-set of JS we could start using on the existing code-base, a bit at a time. The main difficulty I see is hermetic builds. The hosted compiler requires a JS host (NodeJS). There's also in-browser compilation, which we could use to avoid the Node dep.

There is also SystemJS (I mentioned it at the conf), which can load and transpile TypeScript (and CommonJS, AMD, Global) modules in-browser or offline (NodeJS). I like SystemJS a lot, as it solves a number of pain points around vendoring and loading JS modules.

I should also say that I am up for owning some of this stuff at some point. It has been my intention to settle on mostly contributing to the UI once I have some general experience with other parts of the system.

**Comment by edrex** [comment]
React is still marginally hip right? Negative feels there?

I keep poking at Polymer and running away. I can't shake the feeling that it's held together by chewing gum. I love the concept of multi-vendor components coexisting on a page. Also the paper elements would give us a library of ready to go UI components. Not opposed.

I also hear good things about Typescript. Since it's a super-set of JS we could start using on the existing code-base, a bit at a time. The main difficulty I see is hermetic builds. The offline compiler requires a JS host (NodeJS). There's also in-browser compilation, which we could use to avoid the Node dep.

There is also SystemJS (I mentioned it at the conf), which can load and transpile TypeScript (and CommonJS, AMD, Global) modules in-browser or offline (NodeJS). I like SystemJS a lot, as it solves a number of pain points around vendoring and loading JS modules.

I should also say that I am up for owning some of this stuff at some point. It has been my intention to settle on mostly contributing to the UI once I have some general experience with other parts of the system.

**Comment by mpl** [comment]
@bradfitz yes, there's a bunch of bindings at https://github.com/gopherjs/gopherjs/wiki/bindings , including Polymer. And it seems to be actively worked on (furthermore, by PSG-Luna who I believe is an active gopher overall), so Polymer would be an option. There's also Angular, from the same author as gopherjs, but as he says so himself he's too busy with gopherjs these days.

However:

@edrex I was just able to replace a React.DOM.span with something along the lines of js.Global.Get("React").Get("DOM").Call("span", properties, contents) , and it seems to be working (no React error message, and I get the same UI feature). So good call (haha) with that suggestion, thanks!

So it seems we might be able to creep some gopherjs in incrementally, and the "starting from scratch" concern might be a non-issue. :-)

We're left with:

1) (How) Do we deal with the large js file size?
2) Do we see js.Global.Get("React").Get("DOM").Call() as a viable long-term solution, or do we want to move completely off React in the long run?
3) Do we keep on upgrading React in the meantime?

About 2): I like the react model, so if the native Call is not too much of a performance penalty, and still lets us write ok looking Go code, I'm in no hurry to get rid of React.

About 3) I feel like it wouldn't help us much, and it might complicate the job of moving to gopherjs overall. The question is: is there a new UI feature that someone strongly wants to add right now, and that can't be done with the version of React we have right atm?

**Comment by martine** [comment]
Hey, thanks for thinking of me!

TypeScript is a really strong, simple engineering choice.  It is designed to interoperate with existing JavaScript and you can in theory convert a file at a time.  In particular if you're interested in minification, I work on https://github.com/angular/tsickle which compiles TypeScript via the Closure compiler, which is significantly better than any other optimizer.

However, it's not a good choice unless you have someone enthusiastic about fiddling with typecheckng and frontend code, and it sounds like you don't.  And also if gopherjs is even on the table despite its 3mb JS bundles I think your concerns are in a different place than mine.  :)

PS: It sounds to me like on this bug you're mixing a few different problems -- the react upgrade thing seems independent of the gopherjs thing.  You may as well do the former while you figure out the other.  Even if you're writing JavaScript in Go, you still have all the same problems a JS developer has and React solves some important ones.

**Comment by mpl** [comment]
@martine We are indeed addressing different problems at the same time, but I still think they are related as: it's not worth upgrading React if 1) we decide to dump it altogether right now (unlikely), or 2) upgrading it (gains us nothing and) makes the transition to gopherjs more difficult (I don't know yet).

**Comment by mpl** [comment]
btw, just to put some figures in perspective:

-currently in ui/,
$ du -sch *.js *.html *.css
456K	total

and that 5.7MB (minified) output I had for https://camlistore-review.googlesource.com/6608
, once gziped, goes down to:
1.2M	gopherjs.js.gz

otoh, in that CL, we wind up importing a ton of Camlistore dependencies just because I use a couple of types from pkg/search and pkg/schema. So as an experiment, I could try to see how smaller the output get if I isolate these types in their own packages (or if I simply directly bring them in the gopherjs input code, instead of importing them).

**Comment by mpl** [comment]
Quick experiment mentioned above (patch set 3 of https://camlistore-review.googlesource.com/6608), makes the size of gopherjs.js drop down to:
3.4M	gopherjs.js

and gzipped:
656K	gopherjs.js.gz

So in that specific case, I suppose a short-term win would be to move some of the types of pkg/search to e.g. pkg/types/camtypes

**Comment by cliveb** [comment]
Backing up to coexistence, component.kitchen walks throught a web
components approach with React. (I gathered Jan and Rob are tight with the
Polymer and TypeScript teams).

https://component.kitchen/blog/posts/using-react-app-techniques-at-the-web-component-level-with-redux-virtual-dom-and-jsx

**Comment by mpl** [comment]
Just for kicks, I've also the closure compiler on the gopherjs generated code. It seems worthwhile.

https://github.com/gopherjs/gopherjs/issues/136#issuecomment-220741739

**Comment by edrex** [comment]
I guess a more apples-to-apples size comparison with the current UI would be 
`uglifyjs2 ui/*.js | dd > /dev/null` 147662 bytes
`uglifyjs2 ui/*.js | gzip | dd > /dev/null` 33796 bytes

**Comment by edrex** [comment]
My feels around this:

I think a core web UI built into camlistored binary is important. I would also like to see out-of-process apps taking a larger role in providing UI. Given that aim (which might not be shared?), I think there are a few things core could do to support third party UI:

 - Provide hooks for apps to implement various UI interfaces (node aspects, thumbs, item+items actions, global menu entries, maybe route handlers)
 - Provide client-side helper libs for building standalone app pages. Maybe reusable UI components for search, tree browsing, etc, as well as utility code. It seems like Polymer or React would both be good for encapsulating components, although Polymer is a much better fit as this is the primary design goal.

While I can think of ways of providing these services using a core JS monolith (mostly a bunch of factory functions), it seems to me that a much cleaner architecture would be to keep the system broken up into small modules as it is currently. However, I think we should move from the current Closure modules to ES6 modules. It's really a super straightforward translation, and in the future browsers will be able to load these directly (currently there are polyfills).

I don't mind coding JS but agree that it sucks in a lot of ways. There are various approaches to making it nicer: utility libs like underscore, as well as a huge variety of translators/compilers ("transpilers" i guess). I think an important measure of the fitness of one of these transpilers is how well it interoperates with the rest of the stuff in the JS runtime ecosystem. A big part of this is how it translates between its internal package/module system and CommonJS + ES modules (the System global), as this is the basic unit of encapsulation/reuse. TypeScript scores very highly on this, as they support ES modules out of box. GopherJS ignoring JS modules doesn't seem to be a technical limitation, but more the result of following the Golang "single binary" design (which I love, in the context of servers!). Maybe in the future there will be an output mode for GopherJS that translates Golang packages into ES modules. It doesn't seem technically hard, just counter to the original Golang design.

I think I will attempt to create a proof of concept for this idea using TypeScript, ES modules, and Polymer. If it doesn't fly for core, it can always coexist as an app.

**Comment by mpl** [comment]
@edrex all right, so obviously we still don't know if the gopherjs large size is a problem (it probably is), and more importantly if/how we're going to fix it. And I don't want this indecision to be a blocker in any way for the UI, so if/when you end up needing the React upgrade for the UI, let me know and we'll land it.

Heck, or maybe we'll just land it asap (next week). Worst case scenario we'll just revert it if it causes problems.

**Comment by edrex** [comment]
Thanks @mpl :) I'll have a map aspect patch up pretty soon, but it depends on a describe change too so no hurry.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/9086

**Comment by mpl** [comment]
2b093f38c8841d423d86af33f570fa1bd4495918
