### ISSUE TITLE
Provide automatic DNS names for all users

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#722]
For #701 (automatic TLS certs for users), we also need to make sure all users can have automatic DNS names.

We should use our existing `camlistore.net` domain name and run a DNS server there for all users.

Each user would get `<their-gpg-identity>.camlistore.net` pointed to whatever IP they like if they can solve a challenge that they own the IP & the private key.

**Comment by mdempsky** [comment]
So first, there's a configuration problem. You have two sets of servers (Route 53 and ns1.camlistore.net) both serving authoritatively for camlistore.net, but they're serving different record sets.  Here's how I suggest fixing that:

1. Add an A record like `camnetdns1.camlistore.org A 104.154.231.160` to the camlistore.**org** zone in Route 53.  (Maybe also add `camnetdns2.camlistore.org A 104.154.231.160` if Gandhi insists that you provide two nameservers for camlistore.net.)
2. Change Gandhi to use those servers for camlistore.**net** instead of the current Route 53 servers.

There's also a bug in camnetdns: when responding to a DNS query packet, you need to echo the question that you're responding to.  For example, here's a correct response from Route 53:

    $ dig -t a ns1.camlistore.net @ns-432.awsdns-54.com
    
    ; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> -t a ns1.camlistore.net @ns-432.awsdns-54.com
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 776
    ;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1
    ;; WARNING: recursion requested but not available
    
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 4096
    ;; QUESTION SECTION:
    ;ns1.camlistore.net.                IN      A
    
    ;; ANSWER SECTION:
    ns1.camlistore.net. 300     IN      A       104.154.231.160
    
    ;; AUTHORITY SECTION:
    camlistore.net.             300     IN      NS      ns1.camlistore.net.
    
    ;; Query time: 44 msec
    ;; SERVER: 205.251.193.176#53(205.251.193.176)
    ;; WHEN: Tue May 03 23:27:18 PDT 2016
    ;; MSG SIZE  rcvd: 77

Notice "QUERY: 1" and the "QUESTION SECTION" record.

Here's an incorrect response from camnetdns currently:

    $ dig -t a www.camlistore.net @ns1.camlistore.net

    ; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> -t a www.camlistore.net @ns1.camlistore.net
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26603
    ;; flags: qr aa; QUERY: 0, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

    ;; ANSWER SECTION:
    www.camlistore.net.     300     IN      A       104.154.231.160

    ;; Query time: 40 msec
    ;; SERVER: 104.154.231.160#53(104.154.231.160)
    ;; WHEN: Tue May 03 23:28:17 PDT 2016
    ;; MSG SIZE  rcvd: 46

Notice "QUERY: 0" and the lack of a "QUESTION SECTION".

Also, FWIW, in practice DNS packets never have more than one question, nor do they ask questions about classes other than INET.  You're okay to simply ignoring packets if they don't do that.

Lastly, if you want caches to be able to cache negative responses (optional, but recommended), you should include an SOA record in the authority section when serving nodata and nxdomain responses.  See https://cr.yp.to/djbdns/notes.html#response-parsing for a description of how DNS awkwardly encodes various types of answers.

**Comment by mpl** [comment]
doh, and only now do I notice that we had a bug opened about it, and that @mdempsky had already given us the answer (the missing question section) to what I've just figured out by comparing with my bind server output.

Anyway, it confirms that my CL is probably on the right track then:
https://camlistore-review.googlesource.com/8446

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/8626

**Comment by mpl** [comment]
In follow-up of https://camlistore-review.googlesource.com/8446 , so I don't forget:

TODO(mpl): restrict IP space, check client not using a cheap key to make it harder for attackers
