### ISSUE TITLE
missing `zoneinfo.zip` in cloud-launched instance

### ISSUE THREAD

**Issue by josephholsten** [camlistore/camlistore#736]
I noticed the following error in my logs on a gce launched instance: 
`failed to lookup timezone "America/Los_Angeles": open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory`

Seems like a thing I could easily fix if I had any idea how this whole contraption works. Anyone got time to walk me through it?

**Comment by mpl** [comment]
odd.
it's coming from https://golang.org/pkg/time/#LoadLocation , called in pkg/schema/schema.go if you want to debug this some more.
If not, I'll come back to it later.

**Comment by bradfitz** [comment]
Go looks for zoneinfo.zip in the GOROOT if all else fails.

I'd guess that our Docker container for the GCE launcher is missing the `tzdata` package.

**Comment by mpl** [comment]
@josephholsten The launcher at https://camlistore.org/launch/?WIP=1 (please note the WIP parameter) should now create an instance from an image that has the above fix/CL. Could you please try it out and let me now if that fixes the problem for you?

**Comment by josephholsten** [comment]
I'd love to, but I'm unsure how to deploy this to a running gce server. I'll try to dig into it today.

**Comment by mpl** [comment]
@josephholsten hmm I'm not sure you can do that. If you used our launcher to create the initial instance, it means you'd have to modify the existing systemd Camlistore service to now deploy from the https://storage.googleapis.com/camlistore-release/docker/camlistored-WORKINPROGRESS.tar.gz tarball , instead of https://storage.googleapis.com/camlistore-release/docker/camlistored.tar.gz
I suppose it's doable...

it would be much easier to create a new instance (for another project, if you don't want to delete the existing instance) from the url I gave above.

**Comment by mpl** [comment]
@josephholsten ok, I looked into it just for kicks, and it turns out it's actually pretty easy:

1) ssh into your instance (through the cloud console or however else) 
2) sudo $EDITOR /etc/systemd/system/camlistored.service
3) change the fetched tarball to camlistored-WORKINPROGRESS.tar.gz
4) sudo systemctl daemon-reload
5) sudo systemctl restart camlistored # that might not even be needed because of 4)

**Comment by mpl** [comment]
The launcher is now using an image built at rev e4e0d17def62ee8e700701ad002c6fa6b0ec178d, and should hence now have that fix.
I've only tested that the image deploys properly and the web UI is reachable.
