### ISSUE TITLE
Foursquare import is not throttleling

### ISSUE THREAD

**Issue by srcr** [camlistore/camlistore#764]
I just started my camlistore server and now that I import my foursquare data I find that i get hit by a lot of 304 messages. So I regularly pause the import and restart in a while hoping that I again have access to the API. but ideally the importer should handle this.

`
{"meta":{"code":403,"errorType":"rate_limit_exceeded","errorDetail":"Quota exceeded","requestId":"01234567890abcdef"},"response":{}}
`

**Comment by srcr** [comment]
Just noticed that I'm never going to get all Foursquare content. Each time the importer starts with check 0 so when it gets to downloading the images my 500 API calls for that time are used.

**Comment by mpl** [comment]
I'm curious, why is it that you're hitting that problem, whereas other foursquare users such as @bradfitz , @katepek , (and maybe @willnorris ?), don't?
Are there different foursquare account tiers, and some of them only get a limited number of API calls, while others get unlimited or something? Or is it just that you have more data than they do?

(I'm not dismissing your problem, it indeed seems that we should handle something better in the importer in any case).

**Comment by edrex** [comment]
As I understand it, the foursquare importer:

1. Requests all checkins, in batches (of 100 by default). Those responses include wanted related data (venue, people) except venue photos
   1. For each checkin:
      1. If the checkin venue doesn't have enough photos (default 5), requests venue photos.
      2. Requests each needed photo unauthenticated.

According to https://developer.foursquare.com/overview/ratelimits, userless requests to venue/* come from a much larger pool (5,000/hr/API key). Since the bulk of API requests in the initial import come from this pool, I think we can avoid hitting limits (or at least make the importer see 10x more progress on each run) by changing those requests to omit the token.

**Comment by srcr** [comment]
@mpl I'm not sure why I'm the special one.
Only thing is that I observe this at the moment. But if you have ideas about checking more stuff from my end I'm more than willing.

**Comment by edrex** [comment]
I just pushed up a CL which makes the venue/photos requests userless.

https://camlistore-review.googlesource.com/#/c/6576/

@srcr, since your account seems to be hitting quota limits, it would be awesome if you could test the patch and see if it lets the importer run through on the first try. To test:

 - [Get the code](https://camlistore.org/code)
 - `go run make.go` to make sure your build env is good
 - Checkout the patch above (click "Download", top right, then click to copy the "Checkout" command).
 - `go run make.go && devcam server -wipe` (assumes you're not already running a local camlistored on port 3129)
 - You probably need to create new foursquare API credentials for the localhost URL, unless your existing creds are on localhost
 - Try to import.

**Comment by srcr** [comment]
I have tested it and it is working great for me. I downloaded all my check ins wihtout issue.

`
2016/05/12 16:33:53 foursquare: importing 100 checkins (offset 7300)
2016/05/12 16:34:58 foursquare: importing 42 checkins (offset 7400)
`

**Comment by mpl** [comment]
@srcr thanks for the feedback.
