### ISSUE TITLE
Uploads broken behind reverse proxy with Basic auth

### ISSUE THREAD

**Issue by sllawap** [camlistore/camlistore#816]
I'm running an nginx server in front of Camlistore which uses HTTP Basic authentication.

When attempting to upload a file through the web interface, my authentication data is overwritten, causing Chrome to continuously pop up an "Authentication Required" dialog.

I believe this is being caused by the "Authentication: Token" header added by server_connection.js:576 during the XHR request.

I suspect this behavior regressed in the following changelist: e03d0af04f9e0e229d836786042d0744ff36a605

**Comment by mpl** [comment]
@sllawap thanks, I'll look into it.

**Comment by mpl** [comment]
@sllawap I'm hitting a small parsing ambiguity, so just to be sure: are you saying that in your setup, nginx also performs HTTP basic auth on the request before proxying to the back-end (Camlistore) ?

**Comment by sllawap** [comment]
@mpl, that's correct. Essentially, I'm taking the auth responsibility away from Camlistore and letting Nginx do all of the authentication/authorization. This is so that I can use LDAP/PAM etc for auth.

**Comment by mpl** [comment]
@sllawap I want to think about it some more. We could very well revert the change you pointed out, as I think it's actually not needed anymore (the bug it addressed should be fixed in any recent enough), but I think Brad wanted us to be more in control of the whole Authorization business as how browsers do it is a bit of a black magic.

In any case, in the meantime, would something like https://camlistore-review.googlesource.com/6826 work for you? It means you'd have to set "auth": "none" in your server config file, which seems ok since you're delegating the auth to your proxy.

**Comment by mpl** [comment]
There, I've redone  https://camlistore-review.googlesource.com/6826 a little bit differently, and I think that could work.

We probably need to fix the websocket too in your proxy case though.

**Comment by sllawap** [comment]
Maybe I've just been lucky but, FWIW, this snippet has been working fine for WS:

map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
}
server {
        location /my-search {
                proxy_pass http://$proxy_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_http_version 1.1;
        }
}

**Comment by sllawap** [comment]
@mpl, that did the trick! Uploads are now working with ```auth: "none"``` (which I already had in my server config).

**Comment by mpl** [comment]
@sllawap thanks for the feedback. I'll try to integrate your WS hint into the CL, and then we can see about landing it.

**Comment by mpl** [comment]
@sllawap wait, are you saying that you used the snippet above as part of your nginx config (sorry, I don't know anything about nginx), and that was enough to not get any 40* errors from the websocket connection attempts?

**Comment by sllawap** [comment]
@mpl, that's correct.

The snippet of nginx config above seems to work fine for search queries over WS when ```"auth": "none"``` is defined in server-config.json. I don't see any 4XX errors in my Chrome Developer Tools when using the UI and performing searches.

```
Request URL:wss://[redacted]/my-search/camli/search/ws?authtoken
Request Method:GET
Status Code:101 Switching Protocols
```

Frames continue to come in while the WebSocket remains open:

```
{tag: "_status", status: {version: "2016-06-22-8dcba0c+", sync: {,…},…}}
{tag: "_status", status: {version: "2016-06-22-8dcba0c+", sync: {,…},…}}
{tag: "_status", status: {version: "2016-06-22-8dcba0c+", sync: {,…},…}}
```

I've filed issue #818 for tracking the app discovery issue you mentioned in your comment above and included a patch that solves that problem for my use case.

**Comment by mpl** [comment]
@sllawap great, thanks. this means I won't bother with thinking about websockets for now, since it can be fixed on the proxy side. Or at least, this part can wait for its own, independent CL.

Do you feel comfortable with code review & gerrit? If yes, could you please review https://camlistore-review.googlesource.com/6826 and +1 it if you agree with it, so it does not look like I'm landing it like a cowboy?

**Comment by sllawap** [comment]
@mpl dropped a quick note on the Gerrit review but it looks like Brad is already on top of it. :+1:
