### ISSUE TITLE
Slow permanode attribute lookup in Corpus when a signer is in use

### ISSUE THREAD

**Issue by tajtiattila** [camlistore/camlistore#861]
Corpus caches permanode attributes in a map, but doesn't use this cache
in PermanodeAttrValue, PermanodeHasAttrValue and AppendPermanodeAttrValues if
a signer filter is provided.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/8406

**Comment by mpl** [comment]
@bradfitz a bit more context, to help with reviewing:

in describe.go, doDescribe calls dr.sh.getPermanodeLocation which calls permanodeLocation (location.go). In the common (==corpus) case, we'll call permaAttr.get, which calls a.sh.corpus.PermanodeAttrValue with an owner.

So far, all of our calls/uses of (corpus.go) func (c *Corpus) PermanodeAttrValue were actually without a valid signer, which means we would hit the fast path under "if !signerFilter.Valid() && pm.canUseAttrs(at) {".
That changed with https://camlistore-review.googlesource.com/8048 , which introduced the describe path I outlined above, where we end up calling PermanodeAttrValue with a valid owner.
Moreover, in CL https://camlistore-review.googlesource.com/8049 we're going to make location queries consistent with how describe queries already look up a location. Which means location queries, in the common case, will also use a signer/owner.

Therefore, the end goal of CL https://camlistore-review.googlesource.com/8406 is to make PermanodeAttrValue calls with a signer take as fast a path as possible so that location lookups benefit from that optimization. And so that https://camlistore-review.googlesource.com/8049 would not end up being a big slowdown for the common case.
