### ISSUE TITLE
"camput file" fails silently on EACCES failure

### ISSUE THREAD

**Issue by tytso** [camlistore/camlistore#862]
If, while you are backing up a large directory hierarchy and there is some file that you can't read (because it's mode 700 owned by another user, and you're not root), camput will simply exit quietly.

A quick and easy reproduction can be done with something like "camput file /etc/ssh" as a non-root user.   Files such as ssh_host_rsa_key will be mode 700 owned by root.

**Comment by mpl** [comment]
I think this issue is probably covered by issue #685 and its fix, but we'll see if the CL fixes both.

**Comment by tytso** [comment]
I suspect it probably will.    I wonder if it might be better to continue (or at least have the option to treat as non-fatal) after some errors, such as "file not found" (the user may have deleted the file between the directory scan and when the file was read), the permission denied error, etc.   I'll note BTW that some backup programs will warn if a file has changed size unexpectedly, since that's a hint that the backup of that particular file will have gotten compromised.

Speaking more generally, at some point I wonder if the backup functionality should be moved out of camput, since there are a lot of things that you would probably want to do slightly differently if you are backing up directories versus uploading pictures that you just pulled off of your DSLR.    Hmm... does it make sense to treat "backup" as a kind of importer?

**Comment by mpl** [comment]
I think camput should indeed be viewed as a multi-purpose tool to upload blobs, and not specifically to do backup of directories/filesystems.

There are 3 ways I can think of, to build a fancier backup tool:
1) Build it on top of cam* commands (camput, maybe some camtool and camget calls as well). For example as a script, like you asked for on the mailing-list. Probably the easiest way, but not the most efficient, and might be harder for some specific features.
2) As an app, like the publisher. Building on top of app, pkg/client, pkg/app, pkg/search, etc. Probably the most flexible, but most involved too.
3) As an importer. I'm not sure that fits, since one would expect an importer to get its data from a server, not from the local file system, but why not. Probably easier than 2) if you can figure out a way that fits with the importer model, since we now have more experience with importers. But maybe not as flexible.

**Comment by mpl** [comment]
yeah I've tested with https://camlistore-review.googlesource.com/6256 , and I can confirm it also fixes the EACCES case.
