### ISSUE TITLE
WebUI: link to fullsize image

### ISSUE THREAD

**Issue by DanielHeath** [camlistore/camlistore#899]
As camlistore is my primary backup system, I'm often using the web UI to pick out photos to share.

I'd be keen to have some way of downloading originals (rather than resized versions).

Would a sensible UX be to tick several items in the frontend then have a 'download all as zip' or similar button?

**Comment by mpl** [comment]
Just to be sure, do you know that you can already do that for an individual item? Select it, and click on "View original".

But a similar action is indeed missing for >1 items. I think we could have a "Share" action in the contextual menu, which could let several sub-actions unfold, one of them being "download as zip", yes.

The hard part being of course to actually implement the action, not just the UI buttons. :-)
It's one of the first things I'm interested in adding (which is why we have issue #880 open) once we have fully transitioned to gopherjs. But if you think you can beat us to it by doing it directly in javascript before, please be my guest.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/9086

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/9526
