### ISSUE TITLE
clients/android: camput binary permissions sometimes not applied

### ISSUE THREAD

**Issue by tdilo** [camlistore/camlistore#932]
When reinstalling the uploader application, the file permissions of camput are sometimes not applied correctly - ```camput.bin``` is not made executable. Its permissions are set to 0660 instead. There is no indication in the log that setting of permissions fails.

This appears to happen more frequently with CL 10427 applied, but I've also managed to reproduce it with f437c7b41167be5ba2c4cfa25ad1d6e803a38484 (after about 20 reinstalls...) and d21ecfd24eb7ad8276d2ad54c533d3453b1a4734 (9 reinstalls).

All builds were debug builds, signed with my personal release key, installed with ```adb -r``` on a Nexus 5X with latest Android.

I'll have a look at this the next days.

**Comment by mpl** [comment]
thanks.
how do you check the camput.bin permissions (aside from seeing that camput fails to execute)?
As I was saying in https://camlistore-review.googlesource.com/c/10427/ , I was seeing
-rw-rw---- 1 u0_a153 u0_a153 14634626 2017-06-19 18:57 camput.bin
when using ls in adb shell, but I'm not sure that's reliable (as I dunno how adb shell mount things).
In other words, if the problem we're talking about here does not happen, do you know if adb shell will show rwx instead of rw?

**Comment by mpl** [comment]
Since you say "frequently", and not always, I take it if I tried to install enough times with CL 10427, it would eventually install with the correct permissions?
In any case, if CL 10427 seems to increase the probability of seeing the problem, I'd prefer that we fix #932 (or at least understand it) before merging 10427.

**Comment by tdilo** [comment]
I'm also using ```adb shell``` to check the permissions, and it will show as ```rwx``` when everything runs correctly. On my device, CL 10427 usually works. I just reinstalled a build with it applied seven times for the failure to occur.

I agree that CL 10427 should not be merged until this issue is sorted out.
