### ISSUE TITLE
map aspect: layout issues with markers and map

### ISSUE THREAD

**Issue by tdilo** [camlistore/camlistore#933]
On the newly introduced map aspect (great addition, by the way!), location markers are not drawn at the correct location. It appears they are shifted southwards by a constant pixel offset. Incidentally, the map itself is slightly too large (in height) for the browser window, making a vertical scroll bar appear. The amount of excess map height and map marker shift seem to be the same - it looks like the height of the top menu/search bar is not subtracted where it should be. This happens with both Chromium and Firefox on Linux.

Side note: when using Chromium, clicking on the zoom buttons on the map scrolls down to the bottom of the page, hiding the button for zooming in behind the top menu bar.

**Comment by mpl** [comment]
Thanks, I'll look into it.
I might have inadvertently already fixed that in https://camlistore-review.googlesource.com/c/10467/ but I doubt it.

**Comment by mpl** [comment]
PTAL: https://camlistore-review.googlesource.com/c/10507

**Comment by mpl** [comment]
@tdilo I think i see what you mean for the markers being a bit south, and it seems that it's a different issue from the available height fixed by 10507.
However, for some reason, it seems to be fixed (at least I see the markers a bit more north) after I apply https://camlistore-review.googlesource.com/c/10467/ . Can you please confirm?

**Comment by tdilo** [comment]
I can confirm that 10507 fixes the issues with map height issue and zoom buttons.

With 10467 (patch set 8) applied, the map shows markers at the right positions on all zoom levels.

**Comment by mpl** [comment]
Well, since 10467 is needed to completely fix all the problems reported in this issue, could you please give at least a cursory review of it, so I can merge it?
Please note that I'm already aware that's there's a bug/problem with the orange location rectangle over the antimeridian line, I'm working on it. But all the rest is ready for review I think.

**Comment by mpl** [comment]
And with patchset 9 of 10467 I've fixed the antimeridian bug I was working on, so please do PTAL if you can.

**Comment by tdilo** [comment]
Done. After all, I want to use the improved map as soon as possible! :)

**Comment by mpl** [comment]
thanks, I'm glad you like it. I'd like to have it in before I cut a release for early July. comments addressed.
