### ISSUE TITLE
github out of sync with googlesource master repo

### ISSUE THREAD

**Issue by lindner** [camlistore/camlistore#979]
Not sure how the github mirror is set up, but it's on an outdated commit from 2 weeks ago.  Is the process documented somewhere?

**Comment by mpl** [comment]
No, it's not really documented. it's actually part of the website's code. sometimes it gets wedged, but it hadn't actually happened in a long time. i'll have a look tomorrow. thanks.

**Comment by mpl** [comment]
update on that issue:

one of the docker containers that runs the git command that allows to compute the commit e-mail to send (see show_pretty in website/email-go) was stuck:

48c5509b19b6        camlistore/git              "git show --pretty=on"   12 days ago         Up 12 days                              show_pretty

and i suspect it was blocking the other docker containers to run, notably the one that does the git pull to compute the difference between the gerrit repo and the github repo.

docker stop didn't work, but I managed to force kill it. We'll see if that kicks things back in movement. Attached is the output of docker inspect, in case anyone can spot what was wrong with that container.

Moving forward I think maybe we should add some sort of timeout so the containers die by themselves if wedged. I'll also recheck whether they indeed do block each other from running.

[show_pretty.log](https://github.com/camlistore/camlistore/files/1528359/show_pretty.log)

**Comment by mpl** [comment]
well, that is bad:

Nov 22 05:34:20 camweb.c.camlistore-website.internal dockerd[1439]: time="2017-11-22T05:34:20.757632665Z" level=error msg="error restarting containerd: fork/exec /usr/bin/containerd: cannot allocate memory"
Nov 22 10:25:31 camweb.c.camlistore-website.internal dockerd[1439]: time="2017-11-22T10:25:31.513745047Z" level=info msg="New containerd process, pid: 7076\n"

And indeed, vmstat -a:

procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free  inact active   si   so    bi    bo   in   cs us sy id wa st
 0  0      0  78324 125032 1414640    0    0    43    30    4    5  1  1 97  0  0

so i did a 'systemctl restart docker', and:

procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free  inact active   si   so    bi    bo   in   cs us sy id wa st
 0  0      0 1148120 222468 247932    0    0    44    30    5    0  1  1 97  0  0

yay, docker...

The Google dev console keeps on recommending to upgrade this instance, but it would be annoying to do so just because docker leaks like crazy, and the CPU usage is so low.

It looks like the git commands in containers are now running again (I've sen a git pull), but I haven't seen the push to the github repo yet. If it does not happen soon, i'll just restart the whole website service.

**Comment by mpl** [comment]
There we go. looks like things are syncing up again now.

**Comment by mpl** [comment]
relatedly:

https://camlistore-review.googlesource.com/c/camlistore/+/11906
